"""Python file management utilities for LakehousePlumber."""

import logging
import shutil
from pathlib import Path
from typing import Optional, List, Set


class PythonFileManager:
    """Utility class for managing Python function files in generated directories."""

    def __init__(self, project_root: Path):
        self.project_root = project_root
        self.logger = logging.getLogger(__name__)
        self.copied_files: Set[Path] = set()

    def copy_python_file_with_structure(
        self, 
        module_path: str, 
        output_dir: Path,
        state_manager=None,
        source_yaml: Optional[Path] = None,
        environment: Optional[str] = None,
        pipeline: str = "",
        flowgroup: str = ""
    ) -> List[Path]:
        """
        Copy Python function files with proper directory structure and __init__.py files.
        
        Args:
            module_path: The module path from the YAML configuration (e.g., "functions/get_nation.py")
            output_dir: The output directory where files should be copied
            state_manager: Optional state manager for tracking copied files
            source_yaml: Optional source YAML path for state tracking
            environment: Optional environment for state tracking
            pipeline: Pipeline name for state tracking
            flowgroup: Flowgroup name for state tracking
            
        Returns:
            List of copied file paths
        """
        if not output_dir:
            return []

        copied_files = []
        
        try:
            # Resolve source file path
            source_file = self._resolve_source_file(module_path)
            if not source_file or not source_file.exists():
                self.logger.warning(f"Source file not found: {module_path}")
                return []

            # Extract directory path from module_path
            module_dir = Path(module_path).parent
            
            # Create the directory structure matching the module_path
            functions_dir = output_dir / module_dir
            functions_dir.mkdir(parents=True, exist_ok=True)
            
            # Create __init__.py file in the directory
            init_file = functions_dir / "__init__.py"
            if not init_file.exists():
                init_file.write_text("# Generated package for custom Python functions\n", encoding='utf-8')
                copied_files.append(init_file)
                
                # Track the __init__.py file
                if state_manager and source_yaml and environment:
                    self._track_copied_file(
                        state_manager, init_file, source_yaml, environment, 
                        pipeline, flowgroup, "init_file"
                    )
            
            # Copy the Python file with header
            dest_file = functions_dir / Path(module_path).name
            
            # Add header to copied file
            original_content = source_file.read_text(encoding='utf-8')
            header = f"""# ╔══════════════════════════════════════════════════════════════════════════════╗
# ║                                    WARNING                                   ║
# ║                          DO NOT EDIT THIS FILE DIRECTLY                      ║
# ╠══════════════════════════════════════════════════════════════════════════════╣
# ║ This file was automatically copied from: {module_path:<31}     ║
# ║ during pipeline generation. Any changes made here will be OVERWRITTEN        ║
# ║ on the next generation cycle.                                                ║
# ║                                                                              ║
# ║ To make changes:                                                             ║
# ║ 1. Edit the original file: {module_path:<42}        ║
# ║ 2. Regenerate the pipeline                                                   ║
# ╚══════════════════════════════════════════════════════════════════════════════╝

"""
            dest_file.write_text(header + original_content, encoding='utf-8')
            
            if dest_file not in self.copied_files:
                self.copied_files.add(dest_file)
                copied_files.append(dest_file)
                
                self.logger.info(f"Copied {source_file} to {dest_file}")
                
                # Track the copied Python function file
                if state_manager and source_yaml and environment:
                    self._track_copied_file(
                        state_manager, dest_file, source_yaml, environment, 
                        pipeline, flowgroup, "copied_function"
                    )
            
        except Exception as e:
            self.logger.error(f"Error copying file {module_path}: {e}")
            
        return copied_files

    def _resolve_source_file(self, module_path: str) -> Optional[Path]:
        """
        Resolve the module path to an actual file path.
        
        Args:
            module_path: The module path from YAML (e.g., "functions/get_nation.py")
            
        Returns:
            Path to the source file, or None if not found
        """
        # Handle different path formats
        if module_path.startswith("/"):
            # Absolute path
            return Path(module_path)
        else:
            # Relative path from project root
            return self.project_root / module_path

    def _track_copied_file(self, state_manager, target_path: Path, source_yaml: Path, 
                          environment: str, pipeline: str, flowgroup: str, file_type: str):
        """
        Track the copied file in the state manager.
        
        Args:
            state_manager: The state manager instance
            target_path: Path to the copied file
            source_yaml: Path to the source YAML file
            environment: Environment name
            pipeline: Pipeline name
            flowgroup: Flowgroup name
            file_type: Type of file being tracked
        """
        try:
            # Track the copied file as a generated file
            state_manager.track_generated_file(
                generated_path=target_path,
                source_yaml=source_yaml,
                environment=environment,
                pipeline=pipeline,
                flowgroup=flowgroup,
            )
        except Exception as e:
            self.logger.warning(f"Could not track copied file {target_path}: {e}")

    def get_copied_files(self) -> Set[Path]:
        """Get the set of files that have been copied in this session."""
        return self.copied_files.copy() 